In [5]:
import pandas as pd

# Opening a local csv file

In [7]:
df= pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/placement.csv')
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

# Opening a csv file from url (servers)

In [ ]:
import requests
from io import StringIO

url=""
response = requests.get(url)

data = StringIO(response.text)
df = pd.read_csv(data)

print(df.head())

# Sep parameter(using comma or das)

columns name not defined

In [ ]:
pd.read_csv('', sep='\t', names=['sno','name',...]) 
#sep='\t' for tsv files

# Index_col (making index from existing col )

In [ ]:
pd.read_csv('',index_col='colum_name')

# Header parameter

In [ ]:
pd.read_csv('',header=1)
# when coulmns acts as row

# use_cols(when specifc coulmn needed)

In [11]:
x=pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/Telco_customer_churn.csv',usecols=['CustomerID','Tenure Months'])
x

      CustomerID  Tenure Months
0     3668-QPYBK              2
1     9237-HQITU              2
2     9305-CDSKC              8
3     7892-POOKP             28
4     0280-XJGEX             49
...          ...            ...
7038  2569-WGERO             72
7039  6840-RESVB             24
7040  2234-XADUH             72
7041  4801-JZAZL             11
7042  3186-AJIEK             66

[7043 rows x 2 columns]

# nrows(for chossing specific number of row)

In [13]:
pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/Telco_customer_churn.csv',nrows=100)

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0259-GBZSH,1,United States,California,San Diego,92122,"32.85723, -117.209774",32.857230,-117.209774,Male,...,Month-to-month,Yes,Electronic check,85.65,181.50,Yes,1,73,3878,Product dissatisfaction
96,9601-BRXPO,1,United States,California,San Diego,92129,"32.961064, -117.134917",32.961064,-117.134917,Female,...,Month-to-month,Yes,Bank transfer (automatic),104.95,2566.50,Yes,1,66,3642,Service dissatisfaction
97,6905-NIQIN,1,United States,California,San Diego,92154,"32.578103, -117.012975",32.578103,-117.012975,Male,...,Month-to-month,No,Mailed check,50.65,50.65,Yes,1,76,2431,Don't know
98,5167-ZFFMM,1,United States,California,Indio,92201,"33.713891, -116.237257",33.713891,-116.237257,Male,...,Month-to-month,Yes,Credit card (automatic),90.85,90.85,Yes,1,81,3424,Network reliability
99,4895-TMWIR,1,United States,California,Indian Wells,92210,"33.537646, -116.291089",33.537646,-116.291089,Male,...,Month-to-month,No,Mailed check,19.95,214.75,Yes,1,80,5888,Limited range of services

# If number of row values is more than col

In [14]:
pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/Telco_customer_churn.csv',error_bad_lines=False)

TypeError: read_csv() got an unexpected keyword argument 'error_bad_lines'. Did you mean 'on_bad_lines'?

# Dtype changing

In [ ]:
pd.read_csv('',dtype={'col_nam':int})

# Datatime handeling

In [ ]:
pd.read_csv('',parse_dates=['date'])

# Rename func for col

In [17]:
def rename(name):
    if name=="Female":
        return "F"
    elif name=="Male":
        return "M"
    else:
        return name

In [20]:

rename("Male")

'M'

In [19]:
rename("Female")

'F'

In [26]:
pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/Telco_customer_churn.csv',converters={'Gender':rename}).shape

(7043, 33)

# na_value parameter

In [ ]:
pd.read_csv('',na_values=['Male',])
# already say what values are need to be nan

In [29]:
dfs=pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/Telco_customer_churn.csv',chunksize=5000)

In [30]:
for chunks in dfs:
    print(chunk.shape)

NameError: name 'chunk' is not defined