In [1]:
import pandas as pd
import requests

In [13]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/40381/hscard"

headers = {
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
    "x-rapidapi-key": "00fbb7517emsh1620caca22a77bfp1d0ecdjsn194467302018"
}



response = requests.get(url, headers=headers)
data = response.json()

batsman_df = pd.json_normalize(data['scorecard'], record_path='batsman')
bowler_df = pd.json_normalize(data['scorecard'], record_path='bowler')


bowler_df

,id,overs,maidens,wickets,runs,economy,name,nickname,iscaptain,iskeeper,...,dots,balls,rpb,planid,imageid,premiumvideourl,ispremiumfree,inmatchchange,isoverseas,playingxichange
0,15475,4,0,2,29,7.2,Nisarg Patel,,False,False,...,0,40,0.72,0,0,,False,,False,
1,9748,3.5,0,3,33,8.6,Netravalkar,,False,False,...,0,35,0.94,0,0,,False,,False,
2,11450,3,0,0,34,11.3,Ali Khan,,False,False,...,0,30,1.13,0,0,,False,,False,
3,22901,4,0,2,32,8,Yasir Mohammad,,False,False,...,0,40,0.80,0,0,,False,,False,
4,22531,3,0,2,16,5.3,Vatsal Vaghela,,False,False,...,0,30,0.53,0,0,,False,,False,
5,22891,1,0,0,5,5,Ritwik Behera,,False,False,...,0,10,0.50,0,0,,False,,False,
6,10449,4,0,1,25,6.2,Mark Adair,Mark Adair,False,False,...,0,40,0.62,0,0,,False,,False,
7,10451,4,0,0,24,6,Barry McCarthy,Barry McCarthy,False,False,...,0,40,0.60,0,0,,False,,False,
8,18143,4,1,4,25,6.2,Curtis Campher,Curtis Campher,False,False,...,1,40,0.62,0,0,,False,,False,
9,12769,4,0,0,31,7.8,Simi Singh,Simi Singh,False,False,...,0,40,0.78,0,0,,False,,False,
10,11124,3,0,1,27,9,Benjamin White,Benjamin White,False,False,...,0,30,0.90,0,0,,False,,False,
11,1114,1,0,0,4,4,Paul Stirling,Stirling,False,False,...,0,10,0.40,0,0,,False,,False,

In [12]:

batsman_df

,id,balls,runs,fours,sixes,strkrate,name,nickname,iscaptain,iskeeper,...,videourl,videoid,planid,imageid,premiumvideourl,iscbplusfree,ispremiumfree,inmatchchange,isoverseas,playingxichange
0,1114,5,5,1,0,100,Stirling,,False,False,...,,0,0,0,,False,False,,False,
1,6710,5,10,2,0,200,Balbirnie,,True,False,...,,0,0,0,,False,False,,False,
2,11131,56,84,9,3,150,Lorcan Tucker,,False,False,...,,0,0,0,,False,False,,False,
3,18143,11,17,2,1,154.55,Curtis Campher,,False,False,...,,0,0,0,,False,False,,False,
4,6471,10,5,0,0,50,Getkate,,False,False,...,,0,0,0,,False,False,,False,
5,13309,5,4,0,0,80,Neil Rock,,False,True,...,,0,0,0,,False,False,,False,
6,11129,3,1,0,0,33.33,William McClintock,,False,False,...,,0,0,0,,False,False,,False,
7,10449,4,3,0,0,75,Mark Adair,,False,False,...,,0,0,0,,False,False,,False,
8,12769,11,13,1,0,118.18,Simi Singh,,False,False,...,,0,0,0,,False,False,,False,
9,10451,1,0,0,0,0,Barry McCarthy,,False,False,...,,0,0,0,,False,False,,False,
10,11124,2,2,0,0,100,Benjamin White,,False,False,...,,0,0,0,,False,False,,False,
11,22891,23,16,1,0,69.57,Ritwik Behera,Ritwik Behera,False,False,...,,0,0,0,,False,False,,False,
12,22896,11,11,2,0,100,Ryan Scott,Ryan Scott,False,False,...,,0,0,0,,False,False,,False,
13,14732,27,26,2,1,96.3,Monank Patel,Monank Patel,True,True,...,,0,0,0,,False,False,,False,
14,12788,20,22,1,1,110,Gajanand Singh,Gajanand Singh,False,False,...,,0,0,0,,False,False,,False,
15,20217,16,27,1,2,168.75,Sushant Modani,Sushant Modani,False,False,...,,0,0,0,,False,False,,False,
16,10699,11,11,1,0,100,Marty Kain,Marty Kain,False,False,...,,0,0,0,,False,False,,False,
17,15475,6,10,2,0,166.67,Nisarg Patel,Nisarg Patel,False,False,...,,0,0,0,,False,False,,False,
18,22901,2,0,0,0,0,Yasir Mohammad,Yasir Mohammad,False,False,...,,0,0,0,,False,False,,False,
19,9748,6,5,0,0,83.33,Saurabh Netravalkar,Netravalkar,False,False,...,,0,0,0,,False,False,,False,
20,22531,0,0,0,0,0,Vatsal Vaghela,Vatsal Vaghela,False,False,...,,0,0,0,,False,False,,False,
21,11450,0,0,0,0,0,Ali Khan,Ali Khan,False,False,...,,0,0,0,,False,False,,False,

In [14]:
batsman_df = batsman_df[['name','runs','balls','fours','sixes','strkrate']]
bowler_df = bowler_df[['name','overs','maidens','runs','wickets','economy']]

In [15]:
batsman_df

                   name  runs  balls  fours  sixes strkrate
0              Stirling     5      5      1      0      100
1             Balbirnie    10      5      2      0      200
2         Lorcan Tucker    84     56      9      3      150
3        Curtis Campher    17     11      2      1   154.55
4               Getkate     5     10      0      0       50
5             Neil Rock     4      5      0      0       80
6    William McClintock     1      3      0      0    33.33
7            Mark Adair     3      4      0      0       75
8            Simi Singh    13     11      1      0   118.18
9        Barry McCarthy     0      1      0      0        0
10       Benjamin White     2      2      0      0      100
11        Ritwik Behera    16     23      1      0    69.57
12           Ryan Scott    11     11      2      0      100
13         Monank Patel    26     27      2      1     96.3
14       Gajanand Singh    22     20      1      1      110
15       Sushant Modani    27     16      1      2   168.75
16           Marty Kain    11     11      1      0      100
17         Nisarg Patel    10      6      2      0   166.67
18       Yasir Mohammad     0      2      0      0        0
19  Saurabh Netravalkar     5      6      0      0    83.33
20       Vatsal Vaghela     0      0      0      0        0
21             Ali Khan     0      0      0      0        0

In [16]:
bowler_df

              name overs  maidens  runs  wickets economy
0     Nisarg Patel     4        0    29        2     7.2
1      Netravalkar   3.5        0    33        3     8.6
2         Ali Khan     3        0    34        0    11.3
3   Yasir Mohammad     4        0    32        2       8
4   Vatsal Vaghela     3        0    16        2     5.3
5    Ritwik Behera     1        0     5        0       5
6       Mark Adair     4        0    25        1     6.2
7   Barry McCarthy     4        0    24        0       6
8   Curtis Campher     4        1    25        4     6.2
9       Simi Singh     4        0    31        0     7.8
10  Benjamin White     3        0    27        1       9
11   Paul Stirling     1        0     4        0       4