In [3]:
import pandas as pd

In [6]:
df=pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/credit.csv')

# How big is the data

In [8]:
df.shape

(10000, 10)

# How does the data look like?

In [9]:
df.head()  #give first 5 rows

,transaction_id,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
0,1,84.47,22,Electronics,0,0,66,3,40.0,NaN
1,2,541.82,3,Travel,1,0,87,1,64.0,0.0
2,3,237.01,17,Grocery,0,0,49,1,61.0,0.0
3,4,164.33,4,Grocery,0,1,72,3,34.0,0.0
4,5,30.53,15,Food,0,0,79,0,44.0,0.0

In [10]:
df.sample(5) # random rows from dataset

,transaction_id,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
926,927,56.32,14,Clothing,0,0,83,1,49.0,0.0
8555,8556,204.85,22,Electronics,0,0,25,2,47.0,0.0
756,757,174.20,18,Food,1,0,43,0,24.0,0.0
3429,3430,159.15,20,Electronics,0,0,86,2,29.0,0.0
1717,1718,213.76,21,Travel,0,0,49,1,51.0,0.0

# What is data type of columns?

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transaction_id       10000 non-null  int64
 1   amount               9999 non-null   float64
 2   transaction_hour     10000 non-null  object
 3   merchant_category    10000 non-null  object
 4   foreign_transaction  10000 non-null  int64
 5   location_mismatch    10000 non-null  int64
 6   device_trust_score   10000 non-null  int64
 7   velocity_last_24h    10000 non-null  int64
 8   cardholder_age       9999 non-null   float64
 9   is_fraud             9986 non-null   float64
dtypes: float64(3), int64(5), object(2)
memory usage: 781.4+ KB

# Are there are missing values?

In [12]:
df.isnull().sum()

transaction_id          0
amount                  1
transaction_hour        0
merchant_category       0
foreign_transaction     0
location_mismatch       0
device_trust_score      0
velocity_last_24h       0
cardholder_age          1
is_fraud               14
dtype: int64

# How does tha data look mathematically ?

In [13]:
df.describe()

,transaction_id,amount,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
count,10000.00000,9999.000000,10000.000000,10000.000000,10000.000000,10000.000000,9999.000000,9986.000000
mean,5000.50000,175.948604,0.097900,0.139300,61.735500,2.053100,43.420242,0.015121
std,2886.89568,175.402319,0.297194,2.002572,21.558344,1.985869,15.049549,0.122041
min,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2500.75000,50.900000,0.000000,0.000000,43.000000,1.000000,30.000000,0.000000
50%,5000.50000,122.090000,0.000000,0.000000,62.000000,2.000000,44.000000,0.000000
75%,7500.25000,242.550000,0.000000,0.000000,80.000000,3.000000,56.000000,0.000000
max,10000.00000,1471.040000,1.000000,97.000000,99.000000,60.000000,69.000000,1.000000

# Are there duplicate values ?

In [14]:
df.duplicated().sum()

np.int64(0)

# How is the correlation between cols?

In [21]:
df.corr(numeric_only=True)

,transaction_id,amount,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
transaction_id,1.000000,-0.017668,-0.004254,-0.038016,0.016527,-0.042688,0.010117,-0.010431
amount,-0.017668,1.000000,0.003827,-0.001809,0.009992,-0.004420,0.013288,0.028397
foreign_transaction,-0.004254,0.003827,1.000000,0.000609,0.012736,-0.005420,0.005469,0.185683
location_mismatch,-0.038016,-0.001809,0.000609,1.000000,-0.074536,0.554641,-0.075827,0.173105
device_trust_score,0.016527,0.009992,0.012736,-0.074536,1.000000,-0.059666,0.021972,-0.138067
velocity_last_24h,-0.042688,-0.004420,-0.005420,0.554641,-0.059666,1.000000,-0.066505,0.103451
cardholder_age,0.010117,0.013288,0.005469,-0.075827,0.021972,-0.066505,1.000000,-0.000622
is_fraud,-0.010431,0.028397,0.185683,0.173105,-0.138067,0.103451,-0.000622,1.000000