# Encoding Categorical Variables

### Two types od data:
    1. Nominal data(having no fix order)
    2. Ordinal data(Having fix order eg. marks grade)

In [110]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np

In [111]:
df= pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/covid_dataset.csv',index_col=False)

In [112]:
df

     Age  Gender  Fever   Cough       City Has_Covid
0     56    Male  102.4    Mild     Mumbai        No
1     19  Female  101.6  Strong     Mumbai        No
2     76  Female  102.0    Mild    Kolkata        No
3     65    Male   99.7    Mild  Bangalore        No
4     25  Female  102.1    Mild      Delhi       Yes
..   ...     ...    ...     ...        ...       ...
995   41    Male  102.0    Mild     Mumbai        No
996   76  Female  100.9    Mild      Delhi        No
997   35    Male  100.6    Mild    Kolkata        No
998   13  Female   99.5    Mild    Kolkata       Yes
999   55  Female  102.7  Strong    Kolkata       Yes

[1000 rows x 6 columns]

In [113]:
df= df.iloc[:,3:]

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Cough      1000 non-null   object
 1   City       1000 non-null   object
 2   Has_Covid  1000 non-null   object
dtypes: object(3)
memory usage: 23.6+ KB

In [115]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test= train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [116]:
from sklearn.preprocessing import OrdinalEncoder

In [117]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])

In [118]:
x_train[['Cough']]=oe.fit_transform(x_train[['Cough']])
x_test[['Cough']]=oe.transform(x_test[['Cough']])

# oe.fit_transform(x_train['Cough'])

In [119]:
x_train

     Cough       City
425    1.0      Delhi
665    0.0    Kolkata
426    0.0     Mumbai
290    1.0  Bangalore
359    1.0      Delhi
..     ...        ...
689    1.0     Mumbai
959    0.0    Kolkata
579    0.0  Bangalore
792    1.0    Kolkata
573    0.0     Mumbai

[800 rows x 2 columns]

In [120]:
x_test

     Cough       City
96     1.0      Delhi
695    0.0     Mumbai
998    0.0    Kolkata
196    0.0      Delhi
239    1.0  Bangalore
..     ...        ...
336    0.0  Bangalore
643    0.0  Bangalore
569    1.0      Delhi
296    0.0    Kolkata
15     1.0      Delhi

[200 rows x 2 columns]

# Label Encoding

In [121]:
from sklearn.preprocessing import LabelEncoder

In [122]:
le= LabelEncoder()

In [123]:
le.fit(y_train)

LabelEncoder()

In [124]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [125]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [126]:
y_train

array([0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0])