In [13]:
import pandas as pd 
import numpy as np 
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
df=pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/covid_dataset.csv')

In [4]:
df.head()

   Age  Gender  Fever   Cough       City Has_Covid
0   56    Male  102.4    Mild     Mumbai        No
1   19  Female  101.6  Strong     Mumbai        No
2   76  Female  102.0    Mild    Kolkata        No
3   65    Male   99.7    Mild  Bangalore        No
4   25  Female  102.1    Mild      Delhi       Yes

In [5]:
df.isnull().sum()

Age          0
Gender       0
Fever        0
Cough        0
City         0
Has_Covid    0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['Has_Covid']),df['Has_Covid'],test_size=0.2)

In [11]:
x_train

     Age  Gender  Fever   Cough       City
925   70    Male  101.7  Strong      Delhi
434   39  Female  100.1  Strong    Kolkata
260   72    Male  100.1  Strong    Kolkata
213   23  Female   99.2  Strong     Mumbai
228   20  Female   99.4  Strong     Mumbai
..   ...     ...    ...     ...        ...
998   13  Female   99.5    Mild    Kolkata
741   74    Male   98.3    Mild  Bangalore
538   49  Female  101.1    Mild  Bangalore
160   31    Male   98.2  Strong    Kolkata
667   76  Female   99.4  Strong  Bangalore

[800 rows x 5 columns]

In [12]:
from sklearn.compose import ColumnTransformer

In [15]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',OrdinalEncoder(categories=[['Mild','Strong']]),['Cough']),
    ('tnf2',OneHotEncoder(sparse_output=False, drop='first'),['Gender','City'])
],remainder='passthrough')

In [18]:
transformer.fit_transform(x_train).shape

(800, 7)

In [19]:
transformer.fit_transform(x_test).shape

(200, 7)