In [8]:
import pandas as pd 
import numpy as np 

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [11]:
df= pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/train1.csv')[['Age','Pclass','Fare','Survived']]

In [12]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [14]:
df.isnull().mean()

Age         0.198653
Pclass      0.000000
Fare        0.000000
Survived    0.000000
dtype: float64

In [15]:
df.isnull().sum()

Age         177
Pclass        0
Fare          0
Survived      0
dtype: int64

In [17]:
x =df.drop(columns=['Survived'])
y= df['Survived']

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [19]:
x_train.head()

      Age  Pclass     Fare
331  45.5       1  28.5000
733  23.0       2  13.0000
382  32.0       3   7.9250
704  26.0       3   7.8542
813   6.0       3  31.2750

In [28]:
knn= KNNImputer(n_neighbors=5,weights='distance')
x_train_trf= knn.fit_transform(x_train)
x_test_trf= knn.fit_transform(x_test)

In [29]:
lr = LogisticRegression()
lr.fit(x_train_trf,y_train)
y_pred = lr.predict(x_test_trf)
accuracy_score(y_test,y_pred)

0.7541899441340782

In [22]:
si = SimpleImputer()
x_train_trf1= si.fit_transform(x_train)
x_test_trf1= si.fit_transform(x_test)

In [23]:
lr = LogisticRegression()
lr.fit(x_train_trf1,y_train)
y_pred2 = lr.predict(x_test_trf1)
accuracy_score(y_test,y_pred2)

0.7374301675977654